/**
 * Artifacts API routes for control plane
 *
 * Provides REST endpoints for artifact retrieval:
 * - GET /artifacts/:dispatchId - Get presigned S3 URLs for dispatch artifacts
 */

import { Router } from 'express';
import { ArtifactsHandler } from '../handlers/artifacts.handler.js';
import { authMiddleware, requireScope } from '../middleware/auth.middleware.js';
import { validateRequest } from '../middleware/validation.middleware.js';
import { ArtifactsParamsSchema, ArtifactsQuerySchema } from '../../models/artifacts.model.js';
import type { AuthenticatedRequest } from '../../types/api.js';

export const artifactsRouter = Router();

// All artifacts routes require authentication
artifactsRouter.use(authMiddleware);

/**
 * GET /artifacts/:dispatchId
 * Get presigned S3 URLs for artifacts generated by a dispatch
 */
artifactsRouter.get(
  '/:dispatchId',
  requireScope('status'),
  validateRequest({
    params: ArtifactsParamsSchema,
    query: ArtifactsQuerySchema,
  }),
  (req, res, next) => {
    void ArtifactsHandler.getArtifacts(req as AuthenticatedRequest, res, next);
  }
);
